import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'rekhamittal' at '8/6/15 9:58 AM' with Gradle 2.3
 *
 * @author rekhamittal, @date 8/6/15 9:58 AM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
